spring.application.name=allies-backend

# Cấu hình MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/allies_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update

# Cấu hình JWT
connectsphere.app.jwtSecret=mySecretKey123456789012345678901234567890123456789012345678901234567890
connectsphere.app.jwtExpirationMs=86400000

# Cấu hình WebSocket
spring.websocket.sockjs.enabled=true

# Cấu hình CORS
spring.jpa.open-in-view=false